### ISSUE TITLE
I cannot get same performance with the paper

### ISSUE THREAD

**Issue by Kwonjooeun** [gaozhen16/Source-Code-X.Ma#2]
Thank you for your great job and uploading your code.
I executed your code according to your paper. I set cr(compresive ratio)=1/2 and layers in network same as your paper.
but I cannot get same performance with your paper, where the channel model is mmWave channel. 
Could you please upload your finalized version of code same as your paper?

Thank you so much!

**Comment by scliubit** [comment]
Thanks for your interest. Since the author of this paper has just graduated, the upload process maybe a little bit delayed. I will actively contact with the author and update the code as soon as possible

**Comment by Kwonjooeun** [comment]
I think your network has no problem.
Maybe the 'channel.m' has the key of this degraded performance.
The data generation code(channel.m) is really sophisticated so I am hard to understand all of lines. 
If you think the code update will take a long time, can you update the channel.m code first, please?
I want to test one-ring channel model and mmWave channel model, both.
Could you please upload two channel model data generation codes, 'channel_onering.m' and 'channel_mmWave.m' ?

Thank you so much for your wonderful job.
Have a nice day!

**Comment by scliubit** [comment]
thanks again for your attention. 
I have tried to reproduce the result by myself (with the opensourced codes). i have achieved the same performance as the paper under one-ring scenario, and haven't tried further simulations. Note that the channel model seems to be fully opensourced, as you can change the parameters in `channel.m` to generate different channel matrices (such as one-ring and multi-path channel).
The author said that he haven't upload all the codes of his paper, such as somp algorithm, which can be re-implemented easily.
Sorry for the delay, but im also a little bit busy for the moment.

**Comment by Trx1109** [comment]
Can i get the full code of this paper.

**Comment by scliubit** [comment]
that's all he had provided. maybe you can describe your concerns in detail.

**Comment by Trx1109** [comment]
Can i get your email to talk about this paper more detail. Because i do case study about this problem.
Have a nice day
,

**Comment by scliubit** [comment]
please kindly refer to the profile page of my account. btw, please dont further comment on this closed issue, since you will bother the users participated in this issue.
